-- MySQL Script generated by MySQL Workbench
-- Thu Apr 14 16:44:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genres` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`countries` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`series` (
  `id` VARCHAR(36) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `status` CHAR(1) NOT NULL,
  `start` DATE NOT NULL,
  `end` DATE NULL,
  `resume` TEXT NULL,
  `rating` DOUBLE NULL,
  `picture` VARCHAR(200) NULL,
  `genre_id` VARCHAR(36) NOT NULL,
  `country_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_series_genres_idx` (`genre_id` ASC) VISIBLE,
  INDEX `fk_series_countries1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_series_genres`
    FOREIGN KEY (`genre_id`)
    REFERENCES `mydb`.`genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_series_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seasons` (
  `number` INT NOT NULL,
  `serie_id` VARCHAR(36) NOT NULL,
  `resume` TEXT NULL,
  `start` DATE NULL,
  `rating` DOUBLE NULL,
  PRIMARY KEY (`number`, `serie_id`),
  INDEX `fk_seasons_series1_idx` (`serie_id` ASC) VISIBLE,
  CONSTRAINT `fk_seasons_series1`
    FOREIGN KEY (`serie_id`)
    REFERENCES `mydb`.`series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`episodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`episodes` (
  `number` INT NOT NULL,
  `season_number` INT NOT NULL,
  `serie_id` VARCHAR(36) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `resume` TEXT NULL,
  `date` DATE NULL,
  `rating` DOUBLE NULL,
  PRIMARY KEY (`number`, `season_number`, `serie_id`),
  INDEX `fk_episodes_seasons1_idx` (`season_number` ASC, `serie_id` ASC) VISIBLE,
  CONSTRAINT `fk_episodes_seasons1`
    FOREIGN KEY (`season_number` , `serie_id`)
    REFERENCES `mydb`.`seasons` (`number` , `serie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artists` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `age` INT NOT NULL,
  `country_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_artists_countries1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_artists_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`series_has_artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`series_has_artists` (
  `serie_id` VARCHAR(36) NOT NULL,
  `artist_id` VARCHAR(36) NOT NULL,
  `character` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`serie_id`, `artist_id`),
  INDEX `fk_series_has_artists_artists1_idx` (`artist_id` ASC) VISIBLE,
  INDEX `fk_series_has_artists_series1_idx` (`serie_id` ASC) VISIBLE,
  CONSTRAINT `fk_series_has_artists_series1`
    FOREIGN KEY (`serie_id`)
    REFERENCES `mydb`.`series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_series_has_artists_artists1`
    FOREIGN KEY (`artist_id`)
    REFERENCES `mydb`.`artists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_has_series` (
  `user_id` VARCHAR(36) NOT NULL,
  `serie_id` VARCHAR(36) NOT NULL,
  `category` CHAR(1) NOT NULL,
  PRIMARY KEY (`user_id`, `serie_id`),
  INDEX `fk_users_has_series_series1_idx` (`serie_id` ASC) VISIBLE,
  INDEX `fk_users_has_series_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_series_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_series_series1`
    FOREIGN KEY (`serie_id`)
    REFERENCES `mydb`.`series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_watched_episodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_watched_episodes` (
  `user_id` VARCHAR(36) NOT NULL,
  `episode_number` INT NOT NULL,
  `season_number` INT NOT NULL,
  `serie_id` VARCHAR(36) NOT NULL,
  `rating` DOUBLE NOT NULL,
  PRIMARY KEY (`user_id`, `episode_number`, `season_number`, `serie_id`),
  INDEX `fk_users_has_episodes_episodes1_idx` (`episode_number` ASC, `season_number` ASC, `serie_id` ASC) VISIBLE,
  INDEX `fk_users_has_episodes_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_episodes_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_episodes_episodes1`
    FOREIGN KEY (`episode_number` , `season_number` , `serie_id`)
    REFERENCES `mydb`.`episodes` (`number` , `season_number` , `serie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
